language: node_js
node_js:
  - "stable"
install:
  - npm install -g mocha
  - npm install -g selenium-webdriver
  - npm install -g mochawesome
  - npm install
before_script:
  - sleep 3 # give gulp background task some time to execute.
script:
  - gulp test
  - gulp open
after_success:
  bash <(curl -s http://htmlpreview.github.com/?https://github.com/baraneetharan/webdriverjs/blob/master/mochawesome-reports/custom_ReportName.html)
