language: node_js
node_js:
  - "0.10"
install:
  - npm install -g mocha
  - npm install -g selenium-webdriver
  - npm install -g mochawesome
  - npm install
before_script:
  - sleep 3 # give gulp background task some time to execute.
script:
  - mocha spec